### ISSUE TITLE
Unable to communicate with websites using command prompt while attempting to use command "bundle"

### ISSUE THREAD

**Issue by baumga34** [NREL/OpenStudio-analysis-gem#3]
Hello,

I am having an issue communicating with the outside world using the command prompt. 

Here is a copy of the command prompts return message after I try "bundle":

C:\OpenStudioSoftware\NREL\OpenStudio-analysis>bundle    <--- Command Prompt Entry

DL is deprecated, please use Fiddle                                        <--- Command Prompt response
Fetching source index from http://rubygems.org/
Retrying source fetch due to error (2/3): Bundler::HTTPError Could not fetch specs from http://rubygems.org/
Retrying source fetch due to error (3/3): Bundler::HTTPError Could not fetch specs from http://rubygems.org/
Could not fetch specs from http://rubygems.org/

**Comment by rHorsey** [comment]
@baumga34 Hi there! I'm assuming from the 2014 time stamp that this issue has been resolved. If that's not the case please reopen the issues. Many thanks.
